name: Docker-Android 自動化測試

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name:  第一步：抓取專案程式碼
      uses: actions/checkout@v3

    - name:  第二步：設定 Java 17 環境
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name:  第三步：啟動 Docker-Android
      run: |
        # 注意：免費的 GitHub 伺服器沒有 KVM 硬體加速，所以我拿掉了 --device /dev/kvm
        # 實體企業專案中，公司會買支援 KVM 的伺服器來跑這個流水線！
        docker run -d -p 4723:4723 -p 6080:6080 -e EMULATOR_DEVICE="Samsung Galaxy S10" -e APPIUM=true -e WEB_VNC=true --name android-container budtmo/docker-android:emulator_11.0

    - name:  第四步：等待系統啟動 (這在無硬體加速環境會稍久)
      run: |
        echo "正在等待 Appium 伺服器就緒..."
        sleep 60
        docker logs android-container | tail -n 15

    - name:  第五步：執行 Java 測試碼
      run: mvn clean test
